[2024-12-16T09:18:08.711+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T09:18:08.728+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_server_status.check_server_status scheduled__2024-12-16T09:16:00+00:00 [queued]>
[2024-12-16T09:18:08.735+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_server_status.check_server_status scheduled__2024-12-16T09:16:00+00:00 [queued]>
[2024-12-16T09:18:08.735+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-16T09:18:08.747+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_server_status> on 2024-12-16 09:16:00+00:00
[2024-12-16T09:18:08.755+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-16T09:18:08.756+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2024-12-16T09:18:08.757+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'check_server_status', 'check_server_status', 'scheduled__2024-12-16T09:16:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/check_server_status.py', '--cfg-path', '/tmp/tmpei5vqj1j']
[2024-12-16T09:18:08.758+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask check_server_status
[2024-12-16T09:18:08.802+0000] {task_command.py:467} INFO - Running <TaskInstance: check_server_status.check_server_status scheduled__2024-12-16T09:16:00+00:00 [running]> on host 878983b0ced3
[2024-12-16T09:18:08.880+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_server_status' AIRFLOW_CTX_TASK_ID='check_server_status' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T09:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T09:16:00+00:00'
[2024-12-16T09:18:08.881+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-16T09:18:08.882+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-16T09:18:08.882+0000] {logging_mixin.py:190} INFO - Current task name:check_server_status state:running start_date:2024-12-16 09:18:08.728583+00:00
[2024-12-16T09:18:08.882+0000] {logging_mixin.py:190} INFO - Dag name:check_server_status and current dag run status:running
[2024-12-16T09:18:08.882+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T09:18:08.883+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/check_server_status.py", line 46, in check_server
    with open('servers.json', 'r') as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'servers.json'
[2024-12-16T09:18:08.901+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-16T09:18:08.902+0000] {logging_mixin.py:190} INFO - Task start:2024-12-16 09:18:08.728583+00:00 end:2024-12-16 09:18:08.901004+00:00 duration:0.172421
[2024-12-16T09:18:08.902+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): check_server_status> dag:<DAG: check_server_status> dagrun:<DagRun check_server_status @ 2024-12-16 09:16:00+00:00: scheduled__2024-12-16T09:16:00+00:00, state:running, queued_at: 2024-12-16 09:18:04.409922+00:00. externally triggered: False>
[2024-12-16T09:18:08.902+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'servers.json'
[2024-12-16T09:18:08.902+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=check_server_status, task_id=check_server_status, run_id=scheduled__2024-12-16T09:16:00+00:00, execution_date=20241216T091600, start_date=20241216T091808, end_date=20241216T091808
[2024-12-16T09:18:08.924+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T09:18:08.924+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task check_server_status ([Errno 2] No such file or directory: 'servers.json'; 79)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/check_server_status.py", line 46, in check_server
    with open('servers.json', 'r') as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'servers.json'
[2024-12-16T09:18:08.970+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-16T09:18:08.992+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-16T09:18:08.994+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
